spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_liquibase
    username: ${USER_NAME}
    password: test_user
  jpa:
    generate-ddl: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        max-concurrency: 3
        concurrency: 2
        retry:
          initial-interval: 5000

app:
  rabbitmq:
    exchange: question
    routingkey: questionkey
    answerQueue: answerQueue
    questionQueue: questionQueue

logging:
  level:
    root: INFO
    org:
      hibernate: ERROR
      springframework:
        web: INFO
