spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: test_user
    password: test_user
  jpa:
    generate-ddl: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

app:
  rabbitmq:
    exchange: question
    routingkey: questionkey
    answerQueue: answerQueue
    questionQueue: questionQueue

logging:
  level:
    root: INFO
    org:
      hibernate: ERROR
      springframework:
        web: INFO
